// console.log(soma(2,4))
let somaFuncao = require("./soma")
let subFuncao = require("./sub")
let diviFuncao = require("./divi")
let multFuncao = require("./mult")

console.log(somaFuncao(1,2))
console.log(multFuncao(1,2))
console.log(subFuncao(1,2))
console.log(multFuncao(1,2))